services:
  vn-market-service:
    container_name: vn-market-service-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8766:8765"
    volumes:
      - ./app:/app/app
    environment:
      - VN_MARKET_SERVICE_HOST=0.0.0.0
      - VN_MARKET_SERVICE_PORT=8765
      - TZ=Asia/Ho_Chi_Minh
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
